// <auto-generated />
using System;
using Inventory.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<bool>("Weighted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78254fac-f870-48e8-8b67-eca11aefd7ce"),
                            Barcode = "147258",
                            CategoryName = "Samsung",
                            Description = "samsung laptop",
                            Name = "laptop",
                            ProductStatus = 2,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("8851fc5e-6b3f-4407-9be0-7f5b439cb78b"),
                            Barcode = "147256",
                            CategoryName = "Lenovo",
                            Description = "lenovo laptop",
                            Name = "laptop",
                            ProductStatus = 2,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("6224f858-1a0e-44f8-b65b-788fe89dfb5e"),
                            Barcode = "147257",
                            CategoryName = "Acer",
                            Description = "acer laptop",
                            Name = "laptop",
                            ProductStatus = 2,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("cd5dcb76-3de9-4fcc-a45f-6bb91345beef"),
                            Barcode = "147255",
                            CategoryName = "Apple",
                            Description = "apple laptop",
                            Name = "laptop",
                            ProductStatus = 2,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("76e19dcf-b4e2-4418-8c20-59644b75916c"),
                            Barcode = "147259",
                            CategoryName = "Dell",
                            Description = "dell laptop",
                            Name = "laptop",
                            ProductStatus = 2,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("db2c61b6-9f1a-432b-ae26-34d059ccd18b"),
                            Barcode = "147239",
                            CategoryName = "Dell",
                            Description = "dell laptop",
                            Name = "laptop",
                            ProductStatus = 3,
                            Weighted = true
                        },
                        new
                        {
                            Id = new Guid("c960b8b7-51ac-41c5-aba9-d7c75a7915f9"),
                            Barcode = "147229",
                            CategoryName = "Dell",
                            Description = "dell laptop",
                            Name = "laptop",
                            ProductStatus = 1,
                            Weighted = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
